Fatorial-fork-pipe: Fatorial-fork-pipe.o
	gcc -o Fatorial-fork-pipe Fatorial-fork-pipe.o

Fatorial-fork-pipe.o: Fatorial-fork-pipe.c
	gcc -c Fatorial-fork-pipe.c -o Fatorial-fork-pipe.o

clean:
	rm Fatorial-fork-pipe Fatorial-fork-pipe.o
